cd /Users/cristina.paniagua/Desktop/EclipseWorkSpace/Tests
mkdir test4_ApplicationSystems
cd test4_ApplicationSystems
mkdir indoorTemp_Provider
mkdir outdoorTemp_Provider
mkdir controlSystem_Provider
mkdir boiler_Consumer
mkdir iHM_Provider
